//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFStudent
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResult
    {
        public int ResultID { get; set; }
        public string Grade { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public string StudentName { get; set; }
        public string SubjectName { get; set; }
    
        public virtual tblStudent tblStudent { get; set; }
        public virtual tblSubject tblSubject { get; set; }
    }
}
