//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFStudent
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSubject
    {
        public tblSubject()
        {
            this.tblResults = new HashSet<tblResult>();
        }
    
        public int SubjectID { get; set; }
        public string SubjectName { get; set; }
        public string Professor { get; set; }
        public string Semestre { get; set; }
    
        public virtual ICollection<tblResult> tblResults { get; set; }
    }
}
