//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFStudent
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudent
    {
        public tblStudent()
        {
            this.tblResults = new HashSet<tblResult>();
        }
    
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public string IndexNumber { get; set; }
        public string City { get; set; }
        public string Adress { get; set; }
        public string JMBG { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string StudentSurname { get; set; }
    
        public virtual ICollection<tblResult> tblResults { get; set; }
    }
}
